---
job: extension
config:
  # this name will be the folder and filename name
  name: "dinov3_foreground_segmentation"
  process:
    - type: 'dinov3_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "output"
      device: mps

      save:
        dtype: float16  # precision to save
        save_every: 50
        max_step_saves_to_keep: 3

      datasets:
        - folder_path: "fg_dataset/images"
          label_path: "fg_dataset/labels"
          cache_latents_to_disk: false
          resolution: [ 768 ]    # Input resolution

      train:
        batch_size: 1          # Increased batch size with more data
        steps: 1000            # More training steps for better convergence
        gradient_accumulation: 4
        optimizer_params:
          weight_decay: 0.05
        optimizer: "adamw"
        lr: 6e-4
        dtype: bf16
        lr_scheduler: "cosine"

      model:
        arch: "dinov3"
        name_or_path: "facebook/dinov3-vitl16-pretrain-lvd1689m"

        num_classes: 2         # BG/FG
        decoder_type: "linear" # Simple linear decoder for testing
        target_size: 768       # Target image resolution
        feature_layers: [-1]  # Last layer only

  # Oxen.ai experiment tracking configuration
  oxen:
    enabled: false  # Disabled for testing

# Metadata
meta:
  name: "dinov3_foreground_segmentation"
  version: '1.0'
  description: "DINOv3 segmentation training test with synthetic data"
  model_type: "vision_transformer"
  task: "segmentation"
